-- Development seed file.
-- Run with: python seed_database.py
-- This resets and populates the main application database.

DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS listings;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE listings (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    dates_available TEXT,
    price DECIMAL NOT NULL,
    image_url VARCHAR(255),
    description TEXT,
    user_id INTEGER NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_listings_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE bookings (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(10) NOT NULL,
    listing_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_bookings_listing FOREIGN KEY (listing_id)
        REFERENCES listings(id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO users (name, email, password) VALUES ('Peter Puffin', 'pp@email.com', '12445778');
INSERT INTO users (name, email, password) VALUES ('Polly Penguin', 'pollyp@email.com', '12345678');
INSERT INTO users (name, email, password) VALUES ('Quentin Quail', 'qq@email.com', '12649670');
INSERT INTO users (name, email, password) VALUES ('Spears Sparrow', 'spears@email.com', '12242650');

INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Clifftop Retreat', '2027-01-01, 2028-12-12', 100.99, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8MC4BiSkd9JxMt3cEdVi4Tj_Xhi9zviXIS4PsGRlPYZMBVnOHMqtPk46D&s=10', 'A fantastic place for a puffin, or maybe a seagull, great views.', 3);
INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Polar Igloo', '2027-01-01, 2028-12-12', 45.99, 'https://www.lightailing.com/cdn/shop/articles/Polar_Igloo_cover.jpg?v=1568024538', 'A marvellous joint, if a bit chilly.', 2);
INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Bush Lovers Bothy', '2027-01-01, 2028-12-12', 75.86, 'https://media.newyorker.com/photos/661e7b9dee3bbf86940d41d9/master/w_2560%2Cc_limit/Keeley-Treehouse.jpg', 'A brilliant abode, get your mud baths in!', 4);

INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-05', '2027-01-10', 'PENDING', 1, 2);
INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-05', '2027-01-12', 'PENDING', 2, 3);
INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-11', '2027-01-13', 'BOOKED', 1, 4);
INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-23', '2027-01-25', 'BOOKED', 3, 1);
