-- The job of this file is to reset all of our important database tables.
-- And add any data that is needed for the tests to run.
-- This is so that our tests, and application, are always operating from a fresh
-- database state, and that tests don't interfere with each other.

-- First, we must delete (drop) all our tables
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS listings;
DROP TABLE IF EXISTS users;

CREATE TABLE "users" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(50) NOT NULL,
	"password" VARCHAR(25) NOT NULL,
	"password_confirm" VARCHAR(25) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "listings" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"dates_avail" TEXT,
	"price" DECIMAL NOT NULL,
	"image_url" VARCHAR(255),
	"description" TEXT,
	"user_id" INTEGER NOT NULL,
	PRIMARY KEY("id"),
    CONSTRAINT "fk_listings_user" FOREIGN KEY ("user_id")
        REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE "bookings" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"start_date" DATE NOT NULL,
	"end_date" DATE NOT NULL,
	"status" VARCHAR(10) NOT NULL,
	"listing_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
	PRIMARY KEY("id"),
    CONSTRAINT "fk_bookings_listing" FOREIGN KEY ("listing_id")
        REFERENCES "listings"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_bookings_user" FOREIGN KEY ("user_id")
        REFERENCES "users"("id") ON DELETE CASCADE
);


-- Finally, we add any records that are needed for the tests to run
INSERT INTO users (name, email, password, password_confirm) VALUES ('Peter Puffin', 'pp@email.com', '12345678', '12345678');
INSERT INTO users (name, email, password, password_confirm) VALUES ('Polly Penguin', 'pollyp@email.com', '12345678', '12345678');
INSERT INTO users (name, email, password, password_confirm) VALUES ('Quentin Quail', 'qq@email.com', '12345678', '12345678');

INSERT INTO listings (name, dates_avail, price, image_url, description, user_id) VALUES ('Clifftop Retreat', '2027-01-01, 2028-12-12', 100.99, 'https://unsplash.com/photos/a-house-on-a-hill-overlooking-the-ocean-XWL5GofX3D4', 'A fantastic place for a puffin, or maybe a seagull, great views.', 1);
INSERT INTO listings (name, dates_avail, price, image_url, description, user_id) VALUES ('Polar Igloo', '2027-01-01, 2028-12-12', 45.99, 'https://unsplash.com/photos/white-and-gray-building-under-blue-sky-during-daytime-O_IXQPGhGTI', 'A marvellous joint, if a bit chilly.', 2);
INSERT INTO listings (name, dates_avail, price, image_url, description, user_id) VALUES ('Bush Lovers Bothy', '2027-01-01, 2028-12-12', 75.86, 'https://unsplash.com/photos/a-tree-house-in-the-middle-of-a-forest-Vbb9mIdNcxI', 'A brilliant abode, get your mud baths in!', 2);

INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-05', '2027-01-10', 'PENDING', 2, 1);
INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-05', '2027-01-10', 'PENDING', 3, 3);;
INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-11', '2027-01-13', 'BOOKED', 3, 1);
