-- Development seed file.
-- Run with: python seed_database.py
-- This resets and populates the main application database.

DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS listings;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE listings (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    dates_available TEXT,
    price DECIMAL NOT NULL,
    image_url VARCHAR(255),
    description TEXT,
    user_id INTEGER NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_listings_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE bookings (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(10) NOT NULL,
    listing_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_bookings_listing FOREIGN KEY (listing_id)
        REFERENCES listings(id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

-- Passwords below are werkzeug scrypt hashes. Plaintext passwords, for signing in during testing:
-- Peter Puffin: 12445778 | Polly Penguin: 12345678 | Quentin Quail: 12649670 | Spears Sparrow: 12242650
INSERT INTO users (name, email, password) VALUES ('Peter Puffin', 'pp@email.com', 'scrypt:32768:8:1$NS42sOePszYHDQW6$9872c8fd9fa3e41bb99f8ad55420e66a2c8f25c6e3ea5cf7b82c51a3e4dc0ae6cbbf145fe64446d619ac33dc2a69685958d8aef19b3912904bcc2732d4dc9693');
INSERT INTO users (name, email, password) VALUES ('Polly Penguin', 'pollyp@email.com', 'scrypt:32768:8:1$d6MNCa3Rq5xTJoVN$f96b93f3289a8b2543ba7c3c778905d6b94f87f2e035f5b2fbb9a47aebccbcd4836afb47f7952dd33b3c7c8633816034398e25cf5255a4f1eaea5015ec2e51b8');
INSERT INTO users (name, email, password) VALUES ('Quentin Quail', 'qq@email.com', 'scrypt:32768:8:1$SpSc2sKn7y7QM7Pd$aeb4f32ae6317a4fb1d1c0eaefe075f6a2334fd681b0c4b4cecfe5f890e78884c7bae7d4eb31f2e7542d83a5b51d767b1361f6caf1838b0671b70444731d853e');
INSERT INTO users (name, email, password) VALUES ('Spears Sparrow', 'spears@email.com', 'scrypt:32768:8:1$lhO1WyJN97O7zdnm$ff0dfcb13b8890460bba985cff78e32696cc8c28995289a371d0cde7f58ef1cabd98a868eb269984da651f6f8122580b9869001a771b74651285f5669e7a08d1');

INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Clifftop Retreat', '2027-01-01, 2028-12-12', 100.99, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8MC4BiSkd9JxMt3cEdVi4Tj_Xhi9zviXIS4PsGRlPYZMBVnOHMqtPk46D&s=10', 'A fantastic place for a puffin, or maybe a seagull, great views.', 3);
INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Polar Igloo', '2027-01-01, 2028-12-12', 45.99, 'https://www.lightailing.com/cdn/shop/articles/Polar_Igloo_cover.jpg?v=1568024538', 'A marvellous joint, if a bit chilly.', 2);
INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Bush Lovers Bothy', '2027-01-01, 2028-12-12', 75.86, 'https://media.newyorker.com/photos/661e7b9dee3bbf86940d41d9/master/w_2560%2Cc_limit/Keeley-Treehouse.jpg', 'A brilliant abode, get your mud baths in!', 4);
INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Coastal Retreat & Sunset Haven', '2027-02-01, 2028-11-30', 185.00, 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80', 'A masterclass of modern architecture hanging on the cliffs. Open to the ocean breeze with dramatic 180-degree sunset views.', 3);
INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Mountain Lodge', '2027-03-01, 2028-10-15', 245.00, 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=1200&q=80', 'A warm timber getaway tucked high in the pine trees. Features an open fireplace and an outdoor cedar hot tub.', 2);
INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Downtown Modern Loft', '2027-01-15, 2028-12-01', 160.00, 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80', 'Sleek industrial architecture in the cultural heart of the city. Brick walls, a rooftop patio, and curated local art.', 4);
INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Desert Oasis Villa', '2027-04-01, 2028-09-30', 290.00, 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80', 'Minimalist concrete architecture framing rugged desert mountains. Deep cold plunge pool and a stargazing deck.', 1);
INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('Lakeside Cabin', '2027-05-01, 2028-08-31', 140.00, 'https://images.unsplash.com/photo-1475483768296-6163e08872a1?auto=format&fit=crop&w=1200&q=80', 'Charming A-frame right on the water''s edge. Includes kayaks, a fire pit, and morning mist over the glass lake.', 2);
INSERT INTO listings (name, dates_available, price, image_url, description, user_id) VALUES ('The Treehouse Canopy', '2027-06-01, 2028-07-31', 210.00, 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80', 'Live among the ferns and redwoods. High-altitude living with modern organic amenities and suspension bridges.', 1);

INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-05', '2027-01-10', 'PENDING', 1, 2);
INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-05', '2027-01-12', 'PENDING', 2, 3);
INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-11', '2027-01-13', 'BOOKED', 1, 4);
INSERT INTO bookings (start_date, end_date, status, listing_id, user_id) VALUES ('2027-01-23', '2027-01-25', 'BOOKED', 3, 1);
